### ISSUE TITLE
Produced font with gradients is only displaying ok in FontGoogles.

### ISSUE THREAD

**Issue by vv-monsalve** [simoncozens/paintcompiler#1]
When using Paintcompiler to add COLRv1 gradients to a font, it works ok generating a font with gradients show ok in FontGoggles, but not in other browser tester pages like [FontDrop](https://fontdrop.info/), [WakamaiFondue](https://wakamaifondue.com/beta/) or [ColorFontCustomizer](https://tools.djr.com/color-font-customizer/).

**Sources to replicate the issue**
The "paintcompiler.zip" attached includes the following:
- `.py` file used
- input font used
- output font

**Command used**
`paintcompiler -p paintcompiler/paint-gradient-k.py --output path/to/output/font path/to/inputn/font`

This test was done when trying to use paintcompiler for a [new COLRv1 font ](https://github.com/fridamedrano/Kalnia-Color/issues/1) currently in development.
[paintcompiler.zip](https://github.com/simoncozens/paintcompiler/files/11876484/paintcompiler.zip)

**Comment by simoncozens** [comment]
Looks fine to me:

<img width="339" alt="Screenshot 2023-06-27 at 07 18 16" src="https://github.com/simoncozens/paintcompiler/assets/106728/aea2d6be-6f61-4996-bddc-8b4d6ac2bb5c">

<img width="744" alt="Screenshot 2023-06-27 at 07 17 40" src="https://github.com/simoncozens/paintcompiler/assets/106728/6633fb74-942e-43b9-8b19-2b8290159230">

<img width="700" alt="Screenshot 2023-06-27 at 07 18 49" src="https://github.com/simoncozens/paintcompiler/assets/106728/4a013602-415b-44d1-818a-75413ca719ee">

Remember to use a browser which supports COLRv1!

**Comment by vv-monsalve** [comment]
> Remember to use a browser which supports COLRv1!

I am, supposedly! Checked with [Chromacheck](https://pixelambacht.nl/chromacheck/) for `Chrome Version 114.0.5735.133 (Official Build) (x86_64)`. I forgot to mention that other Color fonts are working ok on my end in those same test web pages on this browser. 

**Chrome Version 114.0.5735.133**
<img width="1478" alt="Screen Shot 2023-06-27 at 9 47 37" src="https://github.com/simoncozens/paintcompiler/assets/48698976/4b862098-5d16-4819-b061-b08cd549e2ed">


However, checking the font on the same web-tester but on `Firefox v 114.0.2` now it is displaying ok.

**Firefox v 114.0.2**
<img width="1728" alt="Screen Shot 2023-06-27 at 9 47 48" src="https://github.com/simoncozens/paintcompiler/assets/48698976/37abb7e1-4a2f-4685-bf6c-a284eb1588cd">

Which browser did you use?

**Comment by simoncozens** [comment]
I'm also using 114.0.5735.133. Weird.

**Comment by fridamedrano** [comment]
Same with me, I can see the colors in Font Goggles and Firefox, but not on Chrome.
My Chrome version is 115.0.5790.114.

**Comment by simoncozens** [comment]
Could you try it again now? I am re-packing the font with Harfbuzz, which should produce COLR tables that Chrome is happy with. If it is still failing, please put the font in a zip file and attach it to this issue and I will point Chromium people at it.

**Comment by vv-monsalve** [comment]
Brief update. Using the latest test-font in the upstream repository [`Kalnia-Color.ttf`](https://github.com/fridamedrano/Kalnia-Color/blob/main/paintcompiler-test/variable_ttf/Kalnia-Color.ttf) I can confirm it is showing colors in Chrome `Mac - version 115.0.5790.170` and `Win - version 114.0.5735.199` (tested using Parallels).

However, when tested in RenderStack, the gradients differ between the `system` and the `samsa-svg`. The latter matches the expected result.

<img width="1289" alt="Screen Shot 2023-08-08 at 18 50 30" src="https://github.com/simoncozens/paintcompiler/assets/48698976/371870fb-0e7b-4bfc-b577-ec2c2e6e5e1f">

**Comment by vv-monsalve** [comment]
@fridamedrano When we reviewed this yesterday, at some point, we believed what was shown in `samsa-svg` was the expected behavior. However, reconsidering, it would actually be the first one since you want the alpha variation effect.

Closing this issue here since the produced font from PaintCompiler successfully displays colors in Chrome (v115.0.5790.170) and Firefox on every test web page tried. 

Please feel free of reopening it if you have different findings.
