### ISSUE TITLE
Gradients and Axes

### ISSUE THREAD

**Issue by fridamedrano** [simoncozens/paintcompiler#2]
When wanting to only change the gradient depending on the axis of the font, I got the following error:
> TypeError: float() argument must be a string or a real number, not 'dict'

I'm attaching a folder with my code and the complete error that I got in terminal.

In the code attached, I have 2 gradients:
- "GRADIENT2" works perfectly. This one has Alpha control + Gradient Movement depending on the axis.
- "GRADIENT1", has ONLY the Gradient movement and here it's where I get the error. 

Note: The error doesn't happen when doing ONLY the Alpha control.
Is it possible to control the gradient movement without changing the alpha?

Command used:
`paintcompiler --output variable_ttf/output-font.ttf "input-font.ttf"`

[Issue.zip](https://github.com/simoncozens/paintcompiler/files/12309690/Issue.zip)

**Comment by simoncozens** [comment]
I think I've fixed this. I'll release a new version soon.
